[project]
name = "minimal"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "datasets>=4.5.0",
    "einops>=0.8.2",
    "grain>=0.2.15",
    "jax[tpu]==0.9.0",
    "jaxtyping>=0.3.5",
    "optax>=0.2.6",
    "orbax>=0.1.9",
    "orbax-checkpoint>=0.11.32",
    "quax>=0.2.1",
    "sws-config>=0.6.3",
    "tokamax>=0.0.10",
    "tpu-info>=0.8.1",
    "tqdm>=4.67.1",
    "transformers>=5.0.0",
    "wandb>=0.25.0",
]

[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[tool.ruff.lint]
fixable = ["I001", "F401", "UP"]
ignore = ["E402", "E721", "E731", "E741", "F722", "UP038", "E501", "UP035"]
select = ["E", "F", "I001", "UP"]

[tool.ruff.lint.isort]
combine-as-imports = true
lines-after-imports = 2
order-by-type = false

[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true

[tool.uv.sources]
torch = { index = "pytorch-cpu" }
optax = { git = "https://github.com/google-deepmind/optax" }

[dependency-groups]
dev = [
    "flax>=0.12.2",
    "pytest>=9.0.2",
    "torch>=2.10.0",
    "torchax>=0.0.11",
]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]

[tool.pytest.ini_options]
testpaths = ["tests"]
markers = [
    "require_tpu: marks tests that require a TPU",
    "tpu_ci: marks tests intended for TPU CI runs",
]
